#
#  ETE-Sprachen einfügen.
#
insert into ete_language values(1025,'Arabic',0);
insert into ete_language values(1026,'Bulgarian',0);
insert into ete_language values(1027,'Catalan',0);
insert into ete_language values(1028,'Chinese',0);
insert into ete_language values(1029,'Czech',0);
insert into ete_language values(1030,'Danish',0);
insert into ete_language values(1031,'German',1);
insert into ete_language values(1032,'Greek',0);
insert into ete_language values(1033,'English',0);
insert into ete_language values(1034,'Spanish',0);
insert into ete_language values(1035,'Finnish',0);
insert into ete_language values(1036,'French',0);
insert into ete_language values(1037,'Hebrew',0);
insert into ete_language values(1038,'Hungarian',0);
insert into ete_language values(1039,'Icelandic',0);
insert into ete_language values(1040,'Italian',0);
insert into ete_language values(1041,'Japanese',0);
insert into ete_language values(1042,'Korean',0);
insert into ete_language values(1043,'Dutch',0);
insert into ete_language values(1044,'Norwegian',0);
insert into ete_language values(1045,'Polish',0);
insert into ete_language values(1046,'Braz. Portuguese',0);
insert into ete_language values(1047,'Rhaeto-Romanic',0);
insert into ete_language values(1048,'Romanian',0);
insert into ete_language values(1049,'Russian',0);
insert into ete_language values(1050,'Serbian',0);
insert into ete_language values(1051,'Slovak',0);
insert into ete_language values(1052,'Albanian',0);
insert into ete_language values(1053,'Swedish',0);
insert into ete_language values(1054,'Thai',0);
insert into ete_language values(1055,'Turkian',0);
insert into ete_language values(1056,'Urdu',0);
insert into ete_language values(1057,'Bahasa',0);
insert into ete_language values(2052,'Simple Chinese',0);
insert into ete_language values(2055,'Swiss German',0);
insert into ete_language values(2057,'UK English',0);
insert into ete_language values(2058,'Mexic. Spanish',0);
insert into ete_language values(2060,'Belg. French',0);
insert into ete_language values(2064,'Swiss Italian',0);
insert into ete_language values(2067,'Belg. Dutch',0);
insert into ete_language values(2068,'Norwegian (Nynorsk)',0);
insert into ete_language values(2070,'Portuguese',0);
insert into ete_language values(2074,'Croatian',0);
insert into ete_language values(3084,'Can. French',0);
insert into ete_language values(4108,'Swiss French',0);

commit;