#
#  Hersteller einfügen.
#
insert into manufacturer values(1,'Siemens',NULL);
insert into manufacturer values(2,'ABB',NULL);
insert into manufacturer values(3,'not assigned',NULL);
insert into manufacturer values(4,'Albrecht Jung',NULL);
insert into manufacturer values(5,'Bticino',NULL);
insert into manufacturer values(6,'Gebr. Berker',NULL);
insert into manufacturer values(7,'Busch-Jaeger Elektro',NULL);
insert into manufacturer values(8,'GIRA Giersiepen',NULL);
insert into manufacturer values(9,'Hager Electro',NULL);
insert into manufacturer values(10,'INSTA ELEKTRO',NULL);
insert into manufacturer values(11,'LEGRAND Appareillage électrique',NULL);
insert into manufacturer values(12,'Merten',NULL);
insert into manufacturer values(13,'MK Electric',NULL);
insert into manufacturer values(14,'ABB Elettrocondutture',NULL);
insert into manufacturer values(15,'Hanson Plc',NULL);
insert into manufacturer values(16,'Lindner',NULL);
insert into manufacturer values(17,'Heinrich Kopp',NULL);
insert into manufacturer values(18,'NIKO',NULL);
insert into manufacturer values(19,'PRESTO Gebr. Vedder',NULL);
insert into manufacturer values(20,'GEYER AG',NULL);
insert into manufacturer values(21,'CMC Carl Maier',NULL);
insert into manufacturer values(22,'Siedle & Söhne',NULL);
insert into manufacturer values(23,'A. Ahlstrom',NULL);
insert into manufacturer values(24,'Eberle',NULL);
insert into manufacturer values(25,'GEWISS',NULL);
insert into manufacturer values(26,'not assigned',NULL);
insert into manufacturer values(27,'Albert Ackermann',NULL);
insert into manufacturer values(28,'Schupa GmbH',NULL);
insert into manufacturer values(29,'Levy Fils',NULL);
insert into manufacturer values(30,'Feller',NULL);
insert into manufacturer values(31,'LK as',NULL);
insert into manufacturer values(32,'DEHN & SÖHNE',NULL);
insert into manufacturer values(33,'CRABTREE',NULL);
insert into manufacturer values(34,'Doepke',NULL);
insert into manufacturer values(36,'Paul Hochköpper',NULL);
insert into manufacturer values(37,'Altenburger Electronic',NULL);
insert into manufacturer values(38,'Striebel & John',NULL);
insert into manufacturer values(40,'Philips Lighting',NULL);
insert into manufacturer values(41,'Grässlin',NULL);
insert into manufacturer values(42,'Simon',NULL);
insert into manufacturer values(43,'not assigned',NULL);
insert into manufacturer values(44,'VIMAR',NULL);
insert into manufacturer values(45,'FELTEN & GUILLEAUME',NULL);
insert into manufacturer values(46,'Eltako',NULL);
insert into manufacturer values(48,'CERBERUS-GUINARD',NULL);
insert into manufacturer values(49,'Bosch-Siemens Haushaltsgeräte',NULL);
insert into manufacturer values(52,'RITTO-Werk Loh',NULL);
insert into manufacturer values(53,'Power Controls',NULL);
insert into manufacturer values(55,'ZUMTOBEL',NULL);
insert into manufacturer values(56,'not assigned',NULL);
insert into manufacturer values(57,'Phoenix Contact',NULL);
insert into manufacturer values(58,'OBO Bettermann',NULL);
insert into manufacturer values(60,'not assigned',NULL);
insert into manufacturer values(61,'WAGO Kontakttechnik',NULL);
insert into manufacturer values(62,'not assigned',NULL);
insert into manufacturer values(64,'Niessen',NULL);
insert into manufacturer values(65,'TEGUI Electronica',NULL);
insert into manufacturer values(66,'Wieland Electric',NULL);
insert into manufacturer values(67,'Hermann Kleinhuis',NULL);
insert into manufacturer values(68,'not assigned',NULL);
insert into manufacturer values(69,'Stiebel Eltron/Hydrotherm',NULL);
insert into manufacturer values(70,'Popp',NULL);
insert into manufacturer values(71,'Tehalit',NULL);
insert into manufacturer values(72,'Theben-Werk Zeitautomatik',NULL);
insert into manufacturer values(73,'Wilhelm Rutenbeck',NULL);
insert into manufacturer values(75,'Winkhaus',NULL);
insert into manufacturer values(76,'Robert Bosch',NULL);
insert into manufacturer values(77,'not assigned',NULL);
insert into manufacturer values(78,'Somfy',NULL);
insert into manufacturer values(79,'MENNEKES Elektrotechnik',NULL);
insert into manufacturer values(80,'Woertz',NULL);
insert into manufacturer values(81,'Viessmann Werke',NULL);
insert into manufacturer values(82,'Theodor HEIMEIER Metallwerk',NULL);
insert into manufacturer values(83,'Joh. Vaillant',NULL);
insert into manufacturer values(84,'DIEM Electronics',NULL);
insert into manufacturer values(85,'AMP Deutschland',NULL);
insert into manufacturer values(86,'Framatome Connectors Deutschland GmbH',NULL);
insert into manufacturer values(87,'DIEHL GmbH & Co. Controls Division',NULL);
insert into manufacturer values(88,'Grundig E.M.V.',NULL);
insert into manufacturer values(89,'Buderus Heiztechnik GmbH',NULL);
insert into manufacturer values(90,'SEF - ECOTEC',NULL);
insert into manufacturer values(91,'ELVOX Costruzzioni Elettriche SpA',NULL);
insert into manufacturer values(92,'DORMA GmbH + Co. KG',NULL);
insert into manufacturer values(93,'WindowMaster (VELUX)',NULL);
insert into manufacturer values(94,'Walther Werke',NULL);
insert into manufacturer values(95,'ORAS',NULL);
insert into manufacturer values(96,'Satchwell',NULL);
insert into manufacturer values(105,'RTS Automation',NULL);
insert into manufacturer values(213,'LichtVision',NULL);
insert into manufacturer values(214,'O.Y.L. Electronics',NULL);
insert into manufacturer values(215,'Galax System',NULL);
insert into manufacturer values(216,'Disch',NULL);
insert into manufacturer values(217,'Aucoteam',NULL);
insert into manufacturer values(218,'Luxmate Controls',NULL);
insert into manufacturer values(219,'Danfoss',NULL);
insert into manufacturer values(220,'AST GmbH',NULL);
insert into manufacturer values(221,'schaeper AUTOMATION GmbH',NULL);
insert into manufacturer values(222,'WILA Leuchten',NULL);
insert into manufacturer values(223,'Schlaps & Partner',NULL);
insert into manufacturer values(224,'IEL Systems',NULL);
insert into manufacturer values(225,'Lingg & Janke',NULL);
insert into manufacturer values(226,'Hassinger',NULL);
insert into manufacturer values(227,'Sauter',NULL);
insert into manufacturer values(228,'SIMU',NULL);
insert into manufacturer values(229,'Optimus S.A.',NULL);
insert into manufacturer values(230,'MTM Medientechnologie Harry Maier',NULL);
insert into manufacturer values(231,'Realtime Control Systems AG',NULL);
insert into manufacturer values(232,'HTS High Technology Systems AG',NULL);
insert into manufacturer values(233,'Amann GmbH',NULL);
insert into manufacturer values(234,'BERG Energiekontrollsysteme GmbH',NULL);
insert into manufacturer values(235,'Hüppe Form Sonnenschutzsysteme GmbH',NULL);
insert into manufacturer values(236,'INTERTEL S.r.l.',NULL);
insert into manufacturer values(237,'Oventrop KG',NULL);
insert into manufacturer values(238,'Multronic AG',NULL);
insert into manufacturer values(239,'IPAS GmbH',NULL);
insert into manufacturer values(240,'elero GmbH',NULL);
insert into manufacturer values(241,'Ardan Production and Industrial Controls Ltd.',NULL);
insert into manufacturer values(242,'not assigned',NULL);
insert into manufacturer values(243,'not assigned',NULL);
insert into manufacturer values(244,'ELKA Elektronik',NULL);
insert into manufacturer values(245,'ELEKTROANLAGEN D. NAGEL',NULL);
insert into manufacturer values(246,'Tridonic Bauelemente GmbH',NULL);
insert into manufacturer values(247,'Sika Systemtechnik GmbH',NULL);
insert into manufacturer values(248,'Stengler Gesellschaft',NULL);
insert into manufacturer values(249,'ELJO',NULL);
insert into manufacturer values(250,'EIBA s.c.',NULL);
insert into manufacturer values(252,'Hugo Müller',NULL);
insert into manufacturer values(253,'SBT-Landis&Staefa',NULL);
insert into manufacturer values(254,'APT',NULL);
insert into manufacturer values(255,'Techno Trend',NULL);

commit;

