'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Der Quellcode wurde von wsdl automatisch generiert. Version=1.0.3705.0.
'

'<remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="OpcXmlDaSrvSoap", [Namespace]:="http://technosoftware.com/OpcXml/"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ItemRequestSpec))>  _
Public Class OpcXmlDaSrv
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://80.254.186.217/KEP_Sim/OpcDaGateway.asmx"
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/OPCDA/GetProperties", RequestNamespace:="http://opcfoundation.org/webservices/OPCDA/", ResponseNamespace:="http://opcfoundation.org/webservices/OPCDA/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetProperties(<System.Xml.Serialization.XmlElementAttribute("ItemIDs")> ByVal ItemIDs() As ItemIdentifier, <System.Xml.Serialization.XmlElementAttribute("PropertyNames")> ByVal PropertyNames() As System.Xml.XmlQualifiedName, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal LocaleID As String, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ClientRequestHandle As String, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal RequestTimeout As Date, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ItemPath As String, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ReturnAllProperties As Boolean, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ReturnPropertyValues As Boolean, <System.Xml.Serialization.XmlElementAttribute("PropertyList", IsNullable:=true)> ByRef PropertyList() As PropertyReplyList, <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.Invoke("GetProperties", New Object() {ItemIDs, PropertyNames, LocaleID, ClientRequestHandle, RequestTimeout, ItemPath, ReturnAllProperties, ReturnPropertyValues})
        PropertyList = CType(results(1),PropertyReplyList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginGetProperties(ByVal ItemIDs() As ItemIdentifier, ByVal PropertyNames() As System.Xml.XmlQualifiedName, ByVal LocaleID As String, ByVal ClientRequestHandle As String, ByVal RequestTimeout As Date, ByVal ItemPath As String, ByVal ReturnAllProperties As Boolean, ByVal ReturnPropertyValues As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetProperties", New Object() {ItemIDs, PropertyNames, LocaleID, ClientRequestHandle, RequestTimeout, ItemPath, ReturnAllProperties, ReturnPropertyValues}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndGetProperties(ByVal asyncResult As System.IAsyncResult, ByRef PropertyList() As PropertyReplyList, ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        PropertyList = CType(results(1),PropertyReplyList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/OPCDA/Subscribe", RequestNamespace:="http://opcfoundation.org/webservices/OPCDA/", ResponseNamespace:="http://opcfoundation.org/webservices/OPCDA/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function Subscribe(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Options As RequestOptions, <System.Xml.Serialization.XmlElementAttribute("ItemList")> ByVal ItemList() As SubscribeRequestItemList, <System.Xml.Serialization.XmlAttributeAttribute(), System.ComponentModel.DefaultValueAttribute(false)> ByVal ReturnValuesOnReply As Boolean, <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")> ByVal SubscriptionPingRate As String, <System.Xml.Serialization.XmlElementAttribute("RItemList", IsNullable:=true)> ByRef RItemList() As SubscribeReplyItemList, <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError, <System.Xml.Serialization.XmlAttributeAttribute()> ByRef ServerSubHandle As String) As ReplyBase
        Dim results() As Object = Me.Invoke("Subscribe", New Object() {Options, ItemList, ReturnValuesOnReply, SubscriptionPingRate})
        RItemList = CType(results(1),SubscribeReplyItemList())
        Errors = CType(results(2),OPCError())
        ServerSubHandle = CType(results(3),String)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginSubscribe(ByVal Options As RequestOptions, ByVal ItemList() As SubscribeRequestItemList, ByVal ReturnValuesOnReply As Boolean, ByVal SubscriptionPingRate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("Subscribe", New Object() {Options, ItemList, ReturnValuesOnReply, SubscriptionPingRate}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndSubscribe(ByVal asyncResult As System.IAsyncResult, ByRef RItemList() As SubscribeReplyItemList, ByRef Errors() As OPCError, ByRef ServerSubHandle As String) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        RItemList = CType(results(1),SubscribeReplyItemList())
        Errors = CType(results(2),OPCError())
        ServerSubHandle = CType(results(3),String)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/OPCDA/SubscriptionPolledRefresh", RequestNamespace:="http://opcfoundation.org/webservices/OPCDA/", ResponseNamespace:="http://opcfoundation.org/webservices/OPCDA/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function SubscriptionPolledRefresh(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Options As RequestOptions, <System.Xml.Serialization.XmlElementAttribute("ServerSubHandles")> ByVal ServerSubHandles() As String, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal Holdtime As Date, <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")> ByVal Waittime As String, <System.Xml.Serialization.XmlAttributeAttribute(), System.ComponentModel.DefaultValueAttribute(false)> ByVal ReturnAllItems As Boolean, <System.Xml.Serialization.XmlElementAttribute("InvalidServerSubHandles")> ByRef InvalidServerSubHandles() As String, <System.Xml.Serialization.XmlElementAttribute("RItemList", IsNullable:=true)> ByRef RItemList() As ReplyItemList, <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError, <System.Xml.Serialization.XmlAttributeAttribute()> ByRef DataBufferOverflow As Boolean) As ReplyBase
        Dim results() As Object = Me.Invoke("SubscriptionPolledRefresh", New Object() {Options, ServerSubHandles, Holdtime, Waittime, ReturnAllItems})
        InvalidServerSubHandles = CType(results(1),String())
        RItemList = CType(results(2),ReplyItemList())
        Errors = CType(results(3),OPCError())
        DataBufferOverflow = CType(results(4),Boolean)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginSubscriptionPolledRefresh(ByVal Options As RequestOptions, ByVal ServerSubHandles() As String, ByVal Holdtime As Date, ByVal Waittime As String, ByVal ReturnAllItems As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("SubscriptionPolledRefresh", New Object() {Options, ServerSubHandles, Holdtime, Waittime, ReturnAllItems}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndSubscriptionPolledRefresh(ByVal asyncResult As System.IAsyncResult, ByRef InvalidServerSubHandles() As String, ByRef RItemList() As ReplyItemList, ByRef Errors() As OPCError, ByRef DataBufferOverflow As Boolean) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        InvalidServerSubHandles = CType(results(1),String())
        RItemList = CType(results(2),ReplyItemList())
        Errors = CType(results(3),OPCError())
        DataBufferOverflow = CType(results(4),Boolean)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/OPCDA/SubscriptionCancel", RequestNamespace:="http://opcfoundation.org/webservices/OPCDA/", ResponseNamespace:="http://opcfoundation.org/webservices/OPCDA/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Sub SubscriptionCancel(<System.Xml.Serialization.XmlAttributeAttribute()> ByVal ServerSubHandle As String, <System.Xml.Serialization.XmlAttributeAttribute()> ByRef ClientRequestHandle As String)
        Dim results() As Object = Me.Invoke("SubscriptionCancel", New Object() {ServerSubHandle, ClientRequestHandle})
        ClientRequestHandle = CType(results(0),String)
    End Sub
    
    '<remarks/>
    Public Function BeginSubscriptionCancel(ByVal ServerSubHandle As String, ByVal ClientRequestHandle As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("SubscriptionCancel", New Object() {ServerSubHandle, ClientRequestHandle}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Sub EndSubscriptionCancel(ByVal asyncResult As System.IAsyncResult, ByRef ClientRequestHandle As String)
        Dim results() As Object = Me.EndInvoke(asyncResult)
        ClientRequestHandle = CType(results(0),String)
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetStatus(ByVal LocaleID As String, ByVal ClientRequestHandle As String, ByRef Status As ServerStatus) As ReplyBase
        Dim results() As Object = Me.Invoke("GetStatus", New Object() {LocaleID, ClientRequestHandle})
        Status = CType(results(1),ServerStatus)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginGetStatus(ByVal LocaleID As String, ByVal ClientRequestHandle As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetStatus", New Object() {LocaleID, ClientRequestHandle}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndGetStatus(ByVal asyncResult As System.IAsyncResult, ByRef Status As ServerStatus) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Status = CType(results(1),ServerStatus)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Browse", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function Browse( _
                ByVal LocaleID As String,  _
                ByVal ItemPath As String,  _
                <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ItemName As String,  _
                <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef ContinuationPoint As String,  _
                <System.Xml.Serialization.XmlElementAttribute("PropertyNames")> ByVal PropertyNames() As System.Xml.XmlQualifiedName,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ClientRequestHandle As String,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal RequestTimeout As Date,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal MaxElementsReturned As Integer,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal HasChildrenMask As tristate,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal IsItemMask As tristate,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ElementNameFilter As String,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal VendorFilter As String,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ReturnAllProperties As Boolean,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ReturnPropertyValues As Boolean,  _
                <System.Xml.Serialization.XmlElementAttribute("Element", IsNullable:=true)> ByRef Element() As BrowseElement,  _
                <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError,  _
                <System.Xml.Serialization.XmlAttributeAttribute()> ByRef MoreElements As Boolean) As ReplyBase
        Dim results() As Object = Me.Invoke("Browse", New Object() {LocaleID, ItemPath, ItemName, ContinuationPoint, PropertyNames, ClientRequestHandle, RequestTimeout, MaxElementsReturned, HasChildrenMask, IsItemMask, ElementNameFilter, VendorFilter, ReturnAllProperties, ReturnPropertyValues})
        ContinuationPoint = CType(results(1),String)
        Element = CType(results(2),BrowseElement())
        Errors = CType(results(3),OPCError())
        MoreElements = CType(results(4),Boolean)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginBrowse( _
                ByVal LocaleID As String,  _
                ByVal ItemPath As String,  _
                ByVal ItemName As String,  _
                ByVal ContinuationPoint As String,  _
                ByVal PropertyNames() As System.Xml.XmlQualifiedName,  _
                ByVal ClientRequestHandle As String,  _
                ByVal RequestTimeout As Date,  _
                ByVal MaxElementsReturned As Integer,  _
                ByVal HasChildrenMask As tristate,  _
                ByVal IsItemMask As tristate,  _
                ByVal ElementNameFilter As String,  _
                ByVal VendorFilter As String,  _
                ByVal ReturnAllProperties As Boolean,  _
                ByVal ReturnPropertyValues As Boolean,  _
                ByVal callback As System.AsyncCallback,  _
                ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("Browse", New Object() {LocaleID, ItemPath, ItemName, ContinuationPoint, PropertyNames, ClientRequestHandle, RequestTimeout, MaxElementsReturned, HasChildrenMask, IsItemMask, ElementNameFilter, VendorFilter, ReturnAllProperties, ReturnPropertyValues}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndBrowse(ByVal asyncResult As System.IAsyncResult, ByRef ContinuationPoint As String, ByRef Element() As BrowseElement, ByRef Errors() As OPCError, ByRef MoreElements As Boolean) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        ContinuationPoint = CType(results(1),String)
        Element = CType(results(2),BrowseElement())
        Errors = CType(results(3),OPCError())
        MoreElements = CType(results(4),Boolean)
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Read", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function Read(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Options As RequestOptions, <System.Xml.Serialization.XmlElementAttribute("ItemList")> ByVal ItemList() As ReadRequestItemList, <System.Xml.Serialization.XmlElementAttribute("ItemValues", IsNullable:=true)> ByRef ItemValues() As ReplyItemList, <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.Invoke("Read", New Object() {Options, ItemList})
        ItemValues = CType(results(1),ReplyItemList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginRead(ByVal Options As RequestOptions, ByVal ItemList() As ReadRequestItemList, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("Read", New Object() {Options, ItemList}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndRead(ByVal asyncResult As System.IAsyncResult, ByRef ItemValues() As ReplyItemList, ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        ItemValues = CType(results(1),ReplyItemList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Write", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function Write(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Options As RequestOptions, <System.Xml.Serialization.XmlElementAttribute("ItemList")> ByVal ItemList() As WriteRequestItemList, <System.Xml.Serialization.XmlAttributeAttribute()> ByVal ReturnItemVal As Boolean, <System.Xml.Serialization.XmlElementAttribute("ItemValues", IsNullable:=true)> ByRef ItemValues() As ReplyItemList, <System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable:=true)> ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.Invoke("Write", New Object() {Options, ItemList, ReturnItemVal})
        ItemValues = CType(results(1),ReplyItemList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
    
    '<remarks/>
    Public Function BeginWrite(ByVal Options As RequestOptions, ByVal ItemList() As WriteRequestItemList, ByVal ReturnItemVal As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("Write", New Object() {Options, ItemList, ReturnItemVal}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndWrite(ByVal asyncResult As System.IAsyncResult, ByRef ItemValues() As ReplyItemList, ByRef Errors() As OPCError) As ReplyBase
        Dim results() As Object = Me.EndInvoke(asyncResult)
        ItemValues = CType(results(1),ReplyItemList())
        Errors = CType(results(2),OPCError())
        Return CType(results(0),ReplyBase)
    End Function
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ItemIdentifier
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemPath As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class BrowseElement
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Properties")>  _
    Public Properties() As ItemProperty
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Name As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute("")>  _
    Public ItemPath As String = ""
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public IsItem As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public IsItemSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public HasChildren As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public HasChildrenSpecified As Boolean
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ItemProperty
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Value As Object
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Name As System.Xml.XmlQualifiedName
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Description As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute("")>  _
    Public ItemPath As String = ""
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ErrorID As System.Xml.XmlQualifiedName
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public SuccessID As System.Xml.XmlQualifiedName
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ServerStatus
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public StatusInfo As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public VendorInfo As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("SupportedLocaleIDs")>  _
    Public SupportedLocaleIDs() As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("SupportedInterfaceVersions")>  _
    Public SupportedInterfaceVersions() As interfaceVersion
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public StartTime As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public StartTimeSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public LastUpdateTime As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public LastUpdateTimeSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ProductVersion As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Enum interfaceVersion
    
    '<remarks/>
    XML_DA_Version_1_0
End Enum

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ReplyItemList
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Items", IsNullable:=true)>  _
    Public Items() As ItemValue
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemListHandle As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SubscribeItemValue))>  _
Public Class ItemValue
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Value As Object
    
    '<remarks/>
    Public DiagnosticInfo As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemPath As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ClientItemHandle As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ValueType As System.Xml.XmlQualifiedName
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Timestamp As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public TimestampSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Quality As qualityStatus
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public QualitySpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public LimitBits As limitStatus
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public LimitBitsSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public VendorBits As System.UInt64
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public VendorBitsSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ErrorID As System.Xml.XmlQualifiedName
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public SuccessID As System.Xml.XmlQualifiedName
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Enum qualityStatus
    
    '<remarks/>
    bad
    
    '<remarks/>
    badConfigurationError
    
    '<remarks/>
    badNotConnected
    
    '<remarks/>
    badDeviceFailure
    
    '<remarks/>
    badSensorFailure
    
    '<remarks/>
    badLastKnownValue
    
    '<remarks/>
    badCommFailure
    
    '<remarks/>
    badOutOfService
    
    '<remarks/>
    uncertain
    
    '<remarks/>
    uncertainLastUsableValue
    
    '<remarks/>
    uncertainSensorNotAccurate
    
    '<remarks/>
    uncertainEUExceeded
    
    '<remarks/>
    uncertainSubNormal
    
    '<remarks/>
    good
    
    '<remarks/>
    goodLocalOverride
End Enum

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Enum limitStatus
    
    '<remarks/>
    none
    
    '<remarks/>
    low
    
    '<remarks/>
    high
    
    '<remarks/>
    constant
End Enum

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class SubscribeItemValue
    Inherits ItemValue
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public RevisedSamplingRate As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class SubscribeReplyItemList
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Items", IsNullable:=true)>  _
    Public Items() As SubscribeItemValue
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemListHandle As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public RevisedSamplingRate As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(WriteRequestItemList)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ReadRequestItemList)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(RequestItem)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SubscribeRequestItem)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ReadRequestItem)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SubscribeRequestItemList))>  _
Public Class ItemRequestSpec
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemPath As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ReqType As System.Xml.XmlQualifiedName
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class WriteRequestItemList
    Inherits ItemRequestSpec
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Items")>  _
    Public Items() As ItemValue
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ReadRequestItemList
    Inherits ItemRequestSpec
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Items")>  _
    Public Items() As ReadRequestItem
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public MaxAge As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ReadRequestItem
    Inherits RequestItem
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public MaxAge As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SubscribeRequestItem)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ReadRequestItem))>  _
Public Class RequestItem
    Inherits ItemRequestSpec
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ClientItemHandle As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class SubscribeRequestItem
    Inherits RequestItem
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Deadband As Double
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public DeadbandSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public RequestedSamplingRate As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public EnableBuffering As Boolean = false
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class SubscribeRequestItemList
    Inherits ItemRequestSpec
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Items")>  _
    Public Items() As SubscribeRequestItem
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemListHandle As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Deadband As Double
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public DeadbandSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="duration")>  _
    Public RequestedSamplingRate As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public EnableBuffering As Boolean = false
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class RequestOptions
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public ReturnErrorText As Boolean = true
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public ReturnDiagnosticInfo As Boolean = false
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public ReturnItemTime As Boolean = true
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public ReturnItemName As Boolean = false
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public ReturnItemPath As Boolean = false
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public RequestTimeout As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public RequestTimeoutSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ClientRequestHandle As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public LocaleID As String
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class OPCError
    
    '<remarks/>
    Public [Text] As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ID As System.Xml.XmlQualifiedName
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class PropertyReplyList
    
    '<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Properties")>  _
    Public Properties() As ItemProperty
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemPath As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ItemName As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ErrorID As System.Xml.XmlQualifiedName
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Class ReplyBase
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public RcvTime As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public RcvTimeSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ReplyTime As Date
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public ReplyTimeSpecified As Boolean
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ClientRequestHandle As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public RevisedLocaleID As String
    
    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public ServerState As serverState
    
    '<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public ServerStateSpecified As Boolean
End Class

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Enum serverState
    
    '<remarks/>
    running
    
    '<remarks/>
    failed
    
    '<remarks/>
    noConfig
    
    '<remarks/>
    suspended
    
    '<remarks/>
    test
    
    '<remarks/>
    commFault
End Enum

'<remarks/>
<System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://opcfoundation.org/webservices/OPCDA/")>  _
Public Enum tristate
    
    '<remarks/>
    no
    
    '<remarks/>
    yes
    
    '<remarks/>
    either
End Enum
